export const countries = [
  { value: "at", label: "Austria", areaCode: "+43" },
  { value: "be", label: "Belgium", areaCode: "+32" },
  { value: "bg", label: "Bulgaria", areaCode: "+359" },
  { value: "cl", label: "Chile", areaCode: "+56" },
  { value: "co", label: "Colombia", areaCode: "+57" },
  { value: "cy", label: "Cyprus", areaCode: "+357" },
  { value: "cz", label: "Czech Republic", areaCode: "+420" },
  { value: "dk", label: "Denmark", areaCode: "+45" },
  { value: "ee", label: "Estonia", areaCode: "+372" },
  { value: "fi", label: "Finland", areaCode: "+358" },
  { value: "fr", label: "France", areaCode: "+33" },
  { value: "de", label: "Germany", areaCode: "+49" },
  { value: "gr", label: "Greece", areaCode: "+30" },
  { value: "hu", label: "Hungary", areaCode: "+36" },
  { value: "ie", label: "Ireland", areaCode: "+353" },
  { value: "it", label: "Italy", areaCode: "+39" },
  { value: "lv", label: "Latvia", areaCode: "+371" },
  { value: "lt", label: "Lithuania", areaCode: "+370" },
  { value: "lu", label: "Luxemburg", areaCode: "+352" },
  { value: "mt", label: "Malta", areaCode: "+356" },
  { value: "mx", label: "Mexico", areaCode: "+52" },
  { value: "nl", label: "Netherlands", areaCode: "+31" },
  { value: "no", label: "Norway", areaCode: "+47" },
  { value: "pe", label: "Peru", areaCode: "+51" },
  { value: "pl", label: "Poland", areaCode: "+48" },
  { value: "pt", label: "Portugal", areaCode: "+351" },
  { value: "ro", label: "Romania", areaCode: "+40" },
  { value: "sk", label: "Slovakia", areaCode: "+421" },
  { value: "si", label: "Slovenia", areaCode: "+386" },
  { value: "es", label: "Spain", areaCode: "+34" },
  { value: "se", label: "Sweden", areaCode: "+46" },
  { value: "ch", label: "Switzerland", areaCode: "+41" },
  { value: "gb", label: "United Kingdom", areaCode: "+44" },
  { value: "us", label: "United States", areaCode: "+1" },
];
